### ISSUE TITLE
[Bug]: Duplicated scenes in OBS scene selector

### ISSUE THREAD

**Issue by ux-git** [sircharlo/meeting-media-manager#3219] opened 2024-11-08 10:17 UTC
### What happened?

M3-defined scenes are displayed twice in the list

### To Reproduce

Simply open the scene switcher. 

### What did you expect to happen?

I propose to show three M3-defined scenes first, and then all the others. 

Honestly, I'm not sure whether it's even possible to exclude them from the list, but it would definitely be beneficial for user experience.

### Version

v24.11.0

### What platform are you seeing the problem on?

MacOS

### Screenshots

<img width="530" alt="Screenshot 2024-11-08 at 11 14 15" src="https://github.com/user-attachments/assets/7b17a43c-fa71-43c1-a14b-67f6cac10f49">

**Comment by mtdvlpr** [comment] 2024-11-08 10:37
I can't reproduce this, but it might be fixed in 629ab83aa4ebbae1377f3ba489c13fa7c4195ed2

**Comment by mtdvlpr** [comment] 2024-11-08 10:49
You can test whether this has been fixed now using the latest dev build:

https://github.com/sircharlo/meeting-media-manager/actions/runs/11740546104

**Comment by ux-git** [comment] 2024-11-08 18:13
For me it's always been there. The newest release fixed it, thanks

**Closed** 2024-11-10 04:06 UTC
Labels: bug, implemented
