### ISSUE TITLE
Third monitor

### ISSUE THREAD

**Issue by 6791semaJ** [sircharlo/meeting-media-manager#279] opened 2022-05-04 20:46 UTC
We run 2 monitors at the sound desk and have a third for the Cong to view. I can't seem to get the presentation view on the third monitor. When I move JWMMF from one monitor to the other on the sound desk the presentation view pops up on the other one but never on the one the Cong sees. Is there a way to tell the presentation view where you want it to display?

**Comment by sircharlo** [comment] 2022-05-05 02:32
Not yet (not officially at least), but I’ve started working on a logic flow for this. Stay tuned. 

For now, you can click in the media presentation window, F11, move it to required screen, F11 again, but this isn’t very well supported. 

Something cleaner is coming soon.

**Comment by mjacobus** [comment] 2022-05-05 13:22
I did something similar [here](https://github.com/mjacobus/jw-play/pull/65/files). 

This code snippet might fast track it. I hope it is useful :)

```javascript
const { Menu, screen, app } = require("electron");

class ApplicationMenu {
  constructor(driver) {
    this.driver = driver;
  }

  attach() {
    const menu = Menu.buildFromTemplate(this.getTemplate());
    Menu.setApplicationMenu(menu);
  }

  getTemplate() {
    // ommited
    const driver = this.driver;
    return [
     // 
      {
        label: "Main Window",
        submenu: [
          {
            label: "Move to",
            submenu: this.getMoveToItems(),
          },
          {
            label: "Toggle Fullscreen",
            accelerator: "F",
            click: () => driver.mainWindow.toggleFullScreen(),
          },
        ],
      }
  
    ];
  }

  getMoveToItems() {
    return screen.getAllDisplays().map((display, index) => {
      return {
        label: `Display ${index + 1}`,
        accelerator: `${index + 1}`,
        click: () => {
          this.driver.mainWindow.moveToDisplay(display);
        },
      };
    });
  }
}
```

**Comment by sircharlo** [comment] 2022-05-06 13:22
Thanks @mjacobus !

@6791semaJ My setup doesn't have 3 screens, so progress is slow, but I'm almost there. Stay tuned. New updated planned for today.

**Comment by 6791semaJ** [comment] 2022-05-06 14:01
Thank you so much, your hard work is very much appreciated

**Comment by sircharlo** [comment] 2022-05-07 00:53
Please try with the latest version that will be published within the hour and let me know how/if it works for you. It's rudimentary, but I'll flesh it out more in the future when I have a bit of time.

**Comment by 6791semaJ** [comment] 2022-05-07 07:39
Thanks, I'll give it a go and let you know what happens.

**Comment by 6791semaJ** [comment] 2022-05-08 12:42
I used this this morning. I used F11 to move it on to the third screen, I couldn't find any other way of moving it there.  I had to use the windows task bar to hide and show it, the inbuilt button to do this had no effect whatsoever. Everything else worked perfectly, all the songs and images displayed well with no issues.

**Comment by sircharlo** [comment] 2022-05-08 14:25
Yeah, like i said. F11 isn't really well supported. By the next update, the hide/show wrinkle should be fixed.
Did you see this setting though?

![image](https://user-images.githubusercontent.com/1275666/167300843-e681f6e8-57ea-47fd-8ea4-69d02e2fad31.png)

**Comment by joaochris** [comment] 2022-05-08 18:07
I tested it here, and when switching, the media screen does not go to the selected screen.

**Comment by joaochris** [comment] 2022-05-08 18:17
I tested it and realized that the screens need to be connected before opening the program.

**Comment by sircharlo** [comment] 2022-05-08 18:51
No more, with the latest update.... Building now.
I finally got around to testing with 3 screens, so now I can confirm that it works for me 😆

**Comment by sircharlo** [comment] 2022-05-08 18:55
Let me know if it works for your setups!

**Comment by joaochris** [comment] 2022-05-09 00:23
I tested it again and everything is ok! I have a question. In what cases is the moving window used?

**Comment by sircharlo** [comment] 2022-05-09 00:51
> I tested it again and everything is ok! I have a question. In what cases is the moving window used?

I'm not sure. I was thinking along the lines of when the media window would be shared over Zoom using simple screen share during a fully remote meeting; I've seen cases where sharing MP4 files directly was disabled for a Zoom account.

**Comment by 6791semaJ** [comment] 2022-05-18 06:31
Hi, sorry for delay we've had our circuit assembly. The box you highlighted is there, but it's not showing the third monitor.
![IMG20220518071541](https://user-images.githubusercontent.com/104940822/168972501-83ceddaa-b96e-48ea-9777-18697050b6bf.jpg)

**Comment by 6791semaJ** [comment] 2022-05-19 06:38
Sorry, my mistake! There's not 3 screens to choose from because it's not listing the screen the app is running in, obvious when you realise. All working perfectly! Thank you so much, your efforts are truly appreciated. May Jehovah continue to bless you.

**Closed** 2022-05-19 09:01 UTC
Labels: awaiting-release
