### ISSUE TITLE
Settings screen temporarily shows errors on load

### ISSUE THREAD

**Issue by joaochris** [sircharlo/meeting-media-manager#859] opened 2022-12-16 14:44 UTC
After completing the settings, when entering the settings screen again, M³ hangs for a few seconds.

**Comment by sircharlo** [comment] 2022-12-16 16:53
Hi there, do you have a video/screenshot of this bug?
Thank you

**Comment by mtdvlpr** [comment] 2022-12-16 17:24
I am aware that the settings screen takes a little longer to load compared to the other screens (it shows an empty screen for max 2 seconds), but that is not really fixable. There's a lot going on when rendering the settings page.

**Comment by joaochris** [comment] 2022-12-16 19:18
> Estou ciente de que a tela de configurações demora um pouco mais para carregar em comparação com as outras telas (mostra uma tela vazia por no máximo 2 segundos), mas isso não é realmente corrigível. Há muita coisa acontecendo ao renderizar a página de configurações.

It opens all the tabs and shows everything red and then comes back. Wouldn't there be a way to remove that? 😄

**Comment by joaochris** [comment] 2022-12-16 19:24
> Hi there, do you have a video/screenshot of this bug? Thank you


https://user-images.githubusercontent.com/76891864/208173508-20e6a9d2-e93c-4d21-8f28-2ab31d06313c.mp4

**Comment by mtdvlpr** [comment] 2022-12-16 22:45
Hmm, I don't think so. I've tried before without success, but I can give it another go. The problem is that your preferences need to be loaded into the screen. Before the preferences are loaded, the screen thinks your preferences are empty and everything is red, but as soon as the preferences are loaded everything is normal. The screen is behaving correctly given the situation. The only way to remedy this is to make the preferences load faster, which is difficult, to say the least.

**Comment by sircharlo** [comment] 2022-12-17 15:30
This always bothered me too (I use "bother" in the weakest sense of the word 😄).
Could the preferences be loaded in the background once on app load, instead of every time the settings button is clicked?
Or alternatively, could the 4 settings panels be displayed closed by default, while in the background the settings get loaded and validated? (Instead of loading open by default, then closing if valid and staying open if invalid.) This would at least feel snappier to the end user, I feel.

**Comment by mtdvlpr** [comment] 2022-12-17 21:23
Hi @joaochris, could you try [this version](https://drive.google.com/drive/folders/1_2CzKieYGaK3LcYrEwzNQgfTpNReOSx9?usp=share_link) and see how you like it?

**Comment by Chipperchap** [comment] 2022-12-17 21:36
As an independent casual observer - I like it! Much nicer cleaner visit to the settings dialogue. 😁

**Comment by joaochris** [comment] 2022-12-17 21:45
> Hi @joaochris, could you try [this version](https://drive.google.com/drive/folders/1_2CzKieYGaK3LcYrEwzNQgfTpNReOSx9?usp=share_link) and see how you like it?

Apparently it got better! But I still think it would look better if it didn't appear as if there was some setting missing or something wrong (when the red indication appears). If I've configured everything correctly, when I click on the settings it loads everything instantly, (if it's possible to do that).

...As the second time you press it, it just loads the settings screen without any indication....

**Comment by mtdvlpr** [comment] 2022-12-17 21:53
You're stilling seeing red? Where? The home icon or the actual form fields?

**Comment by Chipperchap** [comment] 2022-12-17 21:59
This is what I see: [Screenshot](https://capture.dropbox.com/0R2X5VGaQ3OzFgSn)

**Comment by joaochris** [comment] 2022-12-17 22:01
@mtdvlpr  That's what the @Chipperchap 
but mine takes longer to load 😢

**Comment by mtdvlpr** [comment] 2022-12-17 22:02
> This is what I see: [Screenshot](https://capture.dropbox.com/0R2X5VGaQ3OzFgSn)
> 
> It only happens the first time - after that when settings are viewed, it has no red button.

That can be fixed!

**Comment by mtdvlpr** [comment] 2022-12-17 22:23
How about [this version](https://drive.google.com/drive/folders/1_2CzKieYGaK3LcYrEwzNQgfTpNReOSx9?usp=share_link)? (I'm working on linux, for which the transition to the settings page is different somehow)

**Comment by Chipperchap** [comment] 2022-12-17 22:36
[Here ](https://capture.dropbox.com/OceGsiaZQwRyp4FS )is the settings loading first and second times.

**Comment by joaochris** [comment] 2022-12-17 22:48
> 



> How about [this version](https://drive.google.com/drive/folders/1_2CzKieYGaK3LcYrEwzNQgfTpNReOSx9?usp=share_link)? (I'm working on linux, for which the transition to the settings page is different somehow)

It's great now! Thanks :)

**Closed** 2023-01-01 13:20 UTC
Labels: bug, awaiting-release
