### ISSUE TITLE
[Bug]: Can't download media for the week from 2024-08-05

### ISSUE THREAD

**Issue by dagandrew** [sircharlo/meeting-media-manager#2521] opened 2024-07-16 13:32 UTC
### What happened?

I can download media every week before and even after, but not this one, it's just loading and nothing happens. Not even an error. I've checked the folders and it created the folder for the weekend meeting, but not for the midweek one. Maybe it's stuck there.

### To Reproduce

1. Select the Week
2. Click Update Media
3. See error

### What did you expect to happen?

to download the media

### Version

v24.4.0

### What platform are you seeing the problem on?

Windows

**Comment by mtdvlpr** [comment] 2024-07-17 06:33
Hi @dagandrew, thanks for reporting! The issue is that that particular midweek meeting program is making a reference to itself, causing an infinite loop in M3. A release with the fix is underway!

**Comment by mtdvlpr** [comment] 2024-07-17 06:35
@sircharlo, this bug probably also exists in your refactor. See #2524 for the fix.

BTW: Kudos on the refactor! It's really nice. I'm sorry that I couldn't deliver the other refactor...

**Comment by mtdvlpr** [comment] 2024-07-17 08:07
The fix has been released in `v24.4.1`

**Closed by mtdvlpr** 2024-07-17 08:07 UTC
Labels: bug, implemented

**Comment by sircharlo** [comment] 2024-07-23 11:08
> @sircharlo, this bug might also exist in your refactor. See #2524 for the fix.

Thanks! I haven't actually implemented InternalLink fetching just yet. I'm trying to see cases where it would be needed, but from what I see it would be pretty rare. In any case, I'll be sure to add this logic when implementing it. 

> BTW: Kudos on the refactor! It's really nice. I'm sorry that I couldn't deliver the other refactor...

Please don't apologize! You worked so hard on it! Your ideas are a major part of what kept this project going during the period where I could not do much with it. Thank you so much for all your contributions! I, along with everyone who uses the app l, am super grateful ☺️
