### ISSUE TITLE
[Bug]: Incorrect Watchtower songs are downloaded after Memorial week

### ISSUE THREAD

**Issue by mh166** [sircharlo/meeting-media-manager#1730] opened 2023-03-28 20:30 UTC
### What happened?

I went to download the media for our weekend meeting on Sunday, April 16th. And to my big surprise, besides the songs not being in the correct order, we were also suggested a bonus song. 😉 

### To Reproduce

1. Update media for the weekend meeting on 2023-04-16
2. Take a look into the folder
3. Find the following files (in German locale):
```
$ tree
.
├── 03-01 - Lied 96 - Gottes Buch - ein echter Schatz.mp4
├── 04-01 - Absatz 2 - Collage - 1 -  Als Kind hört Jesus seinen Eltern zu - 2 -  Als Jugendlicher hört Jesus zusammen mit seiner Familie aufmerksam zu während in der Synagoge au.jpg
├── 04-02 - Absatz 6 - Collage - 1 -  Eine Schwester schreibt eine Notiz und klebt sie in ihre Bibel - 2 -  Ein Bruder studiert auf seinem Tablet einen Artikel - er markiert Stel.jpg
├── 04-03 - Absatz 14 - Wie können wir feststellen ob wir uns von Gottes Wort formen lassen - Siehe Absatz 14.jpg
├── 04-05 - Lied 95 - Das Licht wird immer heller.mp4
├── 05-01 - Lied 97 - Gottes Wort schenkt Leben.mp4
└── Der Wachtturm Februar 2023 - Wie du mehr vom Bibellesen hast.title
```

### What did you expect to happen?

It should be:
- Song 97 before the Watchtower
- Song 95 after the Watchtower
- Song 96 shouldn't be there at all

### Version

v23.3.2

### What platform are you seeing the problem on?

Windows

**Comment by sircharlo** [comment] 2023-03-28 20:44
Ah yes, I see what happened. We'll fix it for the next release (to be released much before that date).

**Comment by mh166** [comment] 2023-03-28 20:46
PS: Same happens the weeks after. Should've tested it right away.

- 2023-04-23: ✅ 144, ✅ 139, ❌ 141
- 2023-04-30: ❌ 097, ✅ 141, ✅ 140, ❌ 95

**Comment by sircharlo** [comment] 2023-03-28 21:48
@mtdvlpr The problem is with the hardcoded `OFFSET ${2 * weekNr}`. I think we'll have to reqork this to use the "document extract" method, as this allows us to target extracts by document ID. The Multimedia table contains the songs, but they are all assigned to document ID 1, therefore it's unusable.

**Comment by sircharlo** [comment] 2023-03-29 02:40
> @mtdvlpr The problem is with the hardcoded `OFFSET ${2 * weekNr}`. I think we'll have to rework this to use the "document extract" method, as this allows us to target extracts by document ID. The Multimedia table contains the songs, but they are all assigned to document ID 1, therefore it's unusable.

Ugh. I'm beyond frustrated lol. I can't crack it. Instead of the current songs logic, I'm trying to get the multimedia from the MepsDocuments linked from the DocumentExtracts that have the same docId, and add them to the promises list, but something isn't jiving.

**Comment by mtdvlpr** [comment] 2023-03-29 05:05
@sircharlo, I'll give it a go today

**Comment by mtdvlpr** [comment] 2023-03-29 06:36
@sircharlo, comparing the Watchtower of January and February with each other, I think the brothers have simplified it for us. In the Watchtower for February, the songs are included in our images query. We should check if it's also the case for upcoming Watchtowers, but it seems we can remove the song query altogether and just use the images query to get the images and songs.

**Comment by sircharlo** [comment] 2023-03-29 22:55
@mh166 if you want to enable beta updates on your personal computer, the latest beta release will contain the fix for this issue 🙂

**Comment by e-Feitosa** [comment] 2023-03-30 23:48
_This observation may help: If you look at JWL, there seems to be an error, the media is different in these weeks, notice that the songs repeat along with the images._
Pode ser que ajude essa observação: Se observar no JWL, parece existir um erro, está diferente as mídias nessas semanas, observe que as musicas repetem junto com as imagens.

![image](https://user-images.githubusercontent.com/90984283/228988982-2a843d5a-a0aa-4b8c-867b-8dd0969006a5.png)

**Closed** 2023-03-31 18:38 UTC
Labels: bug, implemented

**Comment by mh166** [comment] 2023-03-31 19:43
It does work as excpected now, thanks.

~Although there's one small "problem" (if you can even call it that): you have to clear the folder from the previous files yourself. They won't be removed automatically.~ But if I think about it, that's probably a good thing: if you add custom media to the folder, you don't want it to be gone because you refreshed the media for that week...

So I guess, that's hopefully just a one-time issue that will affect only a few people that are getting the media in advance with the broken version of M³.

Anyway, thanks for your amazing work! 👍
