### ISSUE TITLE
[Feature]: External file storage

### ISSUE THREAD

**Issue by sbscomp** [sircharlo/meeting-media-manager#3107] opened 2024-11-03 15:58 UTC
### Is your feature request related to a problem?

The previous version of MMM allowed to specify a folder where media files would be stored. We have sisters assigned to set up the media in dropbox for the meetings ahead of time (especially for public talks), and it appears this feature is missing from MMM now, which means our brothers have to scramble before the meeting to get everything set up.

### Describe the solution you'd like

Have an option to store media files in the folder of choice. It doesn't have to be the default, but it would be very helpful.

### Describe alternatives you've considered

N/A

**Comment by mtdvlpr** [comment] 2024-11-03 16:37
Duplicate of #2782

**Closed** 2024-11-03 16:38 UTC
Labels: duplicate, enhancement
