### ISSUE TITLE
[Bug]: Button for Play Media

### ISSUE THREAD

**Issue by alanfermtz** [sircharlo/meeting-media-manager#1783] opened 2023-04-12 16:11 UTC
### What happened?

The button does not change to stop when exporting custom images to playlist

### To Reproduce

1. Update Multimedia
2. Select a day (I tried with my days of meeting)
3. Explore with custom images and select the images
4. Go to media screen
5. Rearrange an image the try to play images until bug

### What did you expect to happen?

Show the stop even with this behaviour

### Version

v23.4.0

### What platform are you seeing the problem on?

Windows

### Screenshots

https://user-images.githubusercontent.com/43801184/231517926-77d33de6-4608-45f5-bb0d-32b631bbf795.mp4

**Comment by sircharlo** [comment] 2023-04-12 16:21
Duplicate of #1781

**Closed by sircharlo** 2023-04-12 16:21 UTC
Labels: bug
