### ISSUE TITLE
The video duration is not displayed in the monitored folder

### ISSUE THREAD

**Issue by joaochris** [sircharlo/meeting-media-manager#3358] opened 2024-11-15 22:39 UTC
### What happened?

The video duration is not displayed in the monitored folder

### To Reproduce

Add a video to a monitored folder and notice that the video duration does not appear

### Version

V24.11.3

### What platform are you seeing the problem on?

Windows

### Screenshots

![17317103272296037018354283169376](https://github.com/user-attachments/assets/80cb17e2-d607-430d-948f-e18a5ca501a0)

### Confirmations

- [X] I confirm that I have read the documentation website.
- [X] I confirm that I have searched through the existing issues to make sure my bug report is not a duplicate.
- [X] I confirm that I have searched through the existing discussions to make sure my bug report is not a duplicate.
- [X] If I am using macOS, I confirm that I have executed the Terminal commands found in the <a href="https://sircharlo.github.io/meeting-media-manager/fr/using-at-a-kingdom-hall#additional-steps-for-macos-users" target="_blank">additional steps for macOS users</a> found on the documentation website before submitting this bug report.

**Comment by mtdvlpr** [comment] 2024-11-16 18:30
@joaochris, hmm. I can't seem to replicate this. Does this occur for every video all the time? Could you try some other videos?

**Comment by joaochris** [comment] 2024-11-16 18:34
@mtdvlpr Sim, testei com outros vídeos.

**Comment by mtdvlpr** [comment] 2024-11-16 18:47
Do you have the video open somewhere else while importing it? That could cause an issue.

**Comment by sircharlo** [comment] 2024-11-16 19:33
@mtdvlpr the error was logged in Sentry

**Comment by mtdvlpr** [comment] 2024-11-16 19:36
> @mtdvlpr the error was logged in Sentry

Yeah, that's why I thought the video might be open somewhere EBUSY. The other possibility is that M3 is not given enough permissions to access the watched folder items EACCES.

**Comment by e-Feitosa** [comment] 2024-11-17 00:42
> Could you try on the latest version (v24.11.4)? Could you send a jw link to where I can download the video you tried?

About the time of the video, in current version 24.11.4, I added two videos in the folder monitored, changed the m3 to the other profile and returned again to the previous one, and the time in the video appeared 00 in a video and the other appeared the correct time, however, closing the M3 and opening, the two files presents the correct time of the video in the M3 thumbnail.

**Comment by mtdvlpr** [comment] 2024-11-17 06:23
I'm assuming your watched folder is a cloud folder (Google Drive, Dropbox, etc). The moment you add a video to the folder, both your cloud service and M3 are going to react to the file and try to interact with it. Only one program can read the file at once, so you're cloud service was busy with the file first and M3 got an error that the file is currently unavailable because another program is using it.

By closing and opening M3 you gave the cloud service enough time to finish reading the file, so that M3 would be able to read the file and get the duration from it.

**Comment by e-Feitosa** [comment] 2024-11-17 19:30
Your explanation makes perfect sense. I believe this was happening because of tests on local machines, where the media was added to the cloud with the M3 open. In our tests here, when the video is added first to the Google Drive (cloud) folder and then the M3 is opened, the video shows the correct duration.

**Comment by sircharlo** [comment] 2024-11-18 14:04
I think the watcher needs to be tweaked to only add an item once it stops growing (while syncing). Stay tuned.

**Comment by mtdvlpr** [comment] 2024-11-18 14:08
> I think the watcher needs to be tweaked to only add an item once it stops growing (while syncing). Stay tuned.

I don't think that's the main issue. What you're describing is brother A having M3 open while brother B uploads a file to the cloud folder. That's a very rare edge case.

I think the problem is when brother A has M3 open and adds a new file to the cloud folder. When that happens, the file is temporarily busy or locked, because the cloud service is uploading the file to the cloud (while it's already fully present locally).

This could be handled by catching the EBUSY error and auto trying again in x time.

**Comment by sircharlo** [comment] 2024-11-18 16:42
I believe chokidar can handle this automatically. If so, fixed in 46123a78d7d27bc4688335f6ebd7b33b34572300.
Please re-open this issue if the problem persists even in the next version.

**Comment by joaochris** [comment] 2024-11-18 21:25
> I believe chokidar can handle this automatically. If so, fixed in 46123a78d7d27bc4688335f6ebd7b33b34572300.
> Please re-open this issue if the problem persists even in the next version.

Ótimo, obrigado :D

**Closed** 2024-11-21 21:55 UTC
Labels: bug, awaiting-release
