### ISSUE TITLE
Problem with other window

### ISSUE THREAD

**Issue by TheTiger72** [sircharlo/meeting-media-manager#2062] opened 2023-07-26 19:47 UTC
### Is your feature request related to a problem?

Yes, in fact when there's the year text in the background on the second screen and I want to move any window over it, the year text remains in the foreground, hiding the window I want to display.

### Describe the solution you'd like

An option should be added to the settings to deactivate the fact that the year text is always in the foreground.

### Describe alternatives you've considered

There's also another problem: the year text doesn't fit properly on the second screen. You'd need to add an option in the settings so that the year text becomes a classic Windows window, with buttons to minimize, close and enlarge it.

**Comment by mtdvlpr** [comment] 2023-07-27 06:29
Hi @TheTiger72, when would it be desirable to put a window on top of the yeartext (2nd window)? You can already hide the yeartext when you want to display something else, like Zoom.

**Comment by mtdvlpr** [comment] 2023-07-27 06:30
For your second problem, could you make a screenshot showing that the yeartext does not fit the second screen?

**Comment by TheTiger72** [comment] 2023-07-27 07:41
> Hi @TheTiger72, when would it be desirable to put a window on top of the yeartext (2nd window)? You can already hide the yeartext when you want to display something else, like Zoom.

For example, when we need to zoom a person on the other screen, this would avoid having to press the button each time to deactivate the display of the year text on the second screen.

**Comment by TheTiger72** [comment] 2023-07-27 07:44
> For your second problem, could you make a screenshot showing that the yeartext does not fit the second screen?

The problem is that on the second screen, my Windows taskbar is still active, so the windows don't arrange themselves correctly. On the other hand, using a classic window with the button to minimize, maximize and close it works perfectly.

**Comment by sircharlo** [comment] 2023-07-27 12:59
> > Hi @TheTiger72, when would it be desirable to put a window on top of the yeartext (2nd window)? You can already hide the yeartext when you want to display something else, like Zoom.
> 
> For example, when we need to zoom a person on the other screen, this would avoid having to press the button each time to deactivate the display of the year text on the second screen.

I'm not sure that this needs to be changed. By making M³ always on top, it ensures that nothing distracting shows up on screen. This is by design.

**Comment by mtdvlpr** [comment] 2023-07-27 13:00
@TheTiger72, is there a reason you keep your taskbar active on the second monitor?

**Comment by TheTiger72** [comment] 2023-07-27 13:22
> > > Hi @TheTiger72, when would it be desirable to put a window on top of the yeartext (2nd window)? You can already hide the yeartext when you want to display something else, like Zoom.
> 
> > 
> 
> > For example, when we need to zoom a person on the other screen, this would avoid having to press the button each time to deactivate the display of the year text on the second screen.
> 
> 
> 
> I'm not sure that this needs to be changed. By making M³ always on top, it ensures that nothing distracting shows up on screen. This is by design.

The only requirement is that the window be full screen and not necessarily in the foreground.

**Comment by TheTiger72** [comment] 2023-07-27 13:24
> @TheTiger72, is there a reason you keep your taskbar active on the second monitor? I would think that media and the yeartext needs to be fullscreen for optimal viewing experience for the brothers and sisters

We can't figure out how to disable the taskbar on the second screen.
But I agree, the text should be full-screen like JW Library, but not in the foreground so that you can easily put windows on top of it. There should be an option in the M3 settings to allow those who want the old way of working to do so.

**Comment by mtdvlpr** [comment] 2023-07-27 13:32
> We can't figure out how to disable the taskbar on the second screen.

Have you tried the following steps?
https://www.laptopmag.com/articles/disable-taskbar-second-monitor-windows

**Comment by TheTiger72** [comment] 2023-07-27 13:40
> > We can't figure out how to disable the taskbar on the second screen.
> 
> 
> 
> Have you tried the following steps?
> 
> https://www.laptopmag.com/articles/disable-taskbar-second-monitor-windows

No, I haven't tested that, we've just reset the computer and hadn't seen that setting, I'll test when I can get the computer back

**Comment by sircharlo** [comment] 2023-07-27 14:00
> But I agree, the text should be full-screen like JW Library, but not in the foreground so that you can easily put windows on top of it. There should be an option in the M3 settings to allow those who want the old way of working to do so.

May I ask, what would be the advantages of allowing users to disable "always on top"?

The way I see it, simpler is always better. The way M³ works now, the yeartext is always on top, unless the user specifically hides it.

Introducing an option to disable "always on top" would allow for scenarios where windows are accidentally shown on the monitors during congregation meetings, thus introducing both distraction for the audience and additional stress for AV support.

**Comment by TheTiger72** [comment] 2023-07-27 14:15
> > But I agree, the text should be full-screen like JW Library, but not in the foreground so that you can easily put windows on top of it. There should be an option in the M3 settings to allow those who want the old way of working to do so.
> 
> 
> 
> May I ask, what would be the advantages of allowing users to disable "always on top"?
> 
> 
> 
> The way I see it, simpler is always better. The way M³ works now, the yeartext is always on top, unless the user _specifically_ hides it. It requires a deliberate action. 
> 
> 
> 
> Introducing an option to disable "always on top" would allow for scenarios where windows are accidentally shown on the monitors during congregation meetings, thus introducing both distraction for the audience and additional stress for AV support. 

If the option can be activated and deactivated, it won't have any impact on those being trained, as we've never had an unwanted window on the second screen. The principle is to be able to put a zoom participant who is participating remotely on the second screen without having to do any additional manipulation to deactivate the display of the year's text, like the way JW Library works.

**Comment by mtdvlpr** [comment] 2023-07-27 14:20
What we do is before the meeting starts we prepare the 2nd Zoom window to be fullscreen behind the yeartext. Then during the meeting we can prepare the Zoom participant by pinning him to the second window. This will put the Zoom participant fullscreen behind the yeartext. And when it is time to show the Zoom participant you only need to hide the yeartext with the button or shortcut (Alt + Z by default). I don't see how it could be easier than this.

**Comment by mtdvlpr** [comment] 2023-07-27 14:21
If you use the OBS or Zoom integration, it would be even easier, because M3 could automatate pinning and unmuting the Zoom participant and automatically hide/show the yeartext.

**Comment by TheTiger72** [comment] 2023-07-27 15:04
Ok, I see, we'll try it with your method, but Zoom integration doesn't seem to work, I just see the option to rename automatically

**Comment by mtdvlpr** [comment] 2023-08-02 05:33
Hi @TheTiger72, the Zoom integration works as follows:
1. You set up the meeting details in settings
2. You start the presentation mode for a certain day
3. A blue toolbar appears just below the normal toolbar
4. M3 will try to join the Zoom meeting and needs co-host privileges
5. You can execute some start and stop meeting actions
6. You can select one or more participants with the dropdown
7. Once selected, you can press the button next to it to automagically pin the participants, hide the yeartext and unmute the participants
8. When you click the same button again, the yeartext will appear and participants will be unpinned and muted

**Comment by TheTiger72** [comment] 2023-08-04 13:52
Hello again, does anyone here have this problem:
When I open JW Library it gets stuck in full screen and I can't move it. To remove it from full screen mode, I have to go to the JW Library settings and deactivate then reactivate the "broadcast on second screen" function. And I have the same problem when I share a screen with Zoom. Thanks

**Comment by mtdvlpr** [comment] 2023-08-04 14:24
I haven't personally encountered this. To ask the community for help, it's best to [create a discussion](https://github.com/sircharlo/meeting-media-manager/discussions/new?category=q-a).

**Comment by TheTiger72** [comment] 2023-08-04 17:48
Ok, thanks

**Comment by sircharlo** [comment] 2023-08-14 17:23
Closing for now, as we aren't planning to change the behaviour of the media window for now.

**Closed by sircharlo** 2023-08-14 17:23 UTC
Labels: enhancement
