### ISSUE TITLE
M3 shows no image being shown when it is being displayed on TVs

### ISSUE THREAD

**Issue by Tdanforth** [sircharlo/meeting-media-manager#1756] opened 2023-04-02 15:52 UTC
### What happened?

When I press the play button on M3 to display an image on the TVs, it will display on the TVs but not show a stop button on M3, just the play button. I have to press the play button again, which repeats displaying the image that is already on the TVs. Then it shows the stop button and then I can stop the image from displaying on the TVs.

### To Reproduce

🤷‍♂️

### What did you expect to happen?

When the play button is displayed on an image, the stop button should display.

### Version

v23.4.0

### What platform are you seeing the problem on?

Windows

### Relevant log output

```shell
{}
```

### Additional context

Windows_NT 10.0.19045 x64
### Anonymized `prefs.json`
```
{
  "app": {
    "autoOpenFolderWhenDone": false,
    "autoQuitWhenDone": false,
    "autoRunAtBoot": true,
    "autoStartSync": true,
    "betaUpdates": false,
    "congregationName": "West Hills",
    "customCachePath": null,
    "disableAutoUpdate": false,
    "disableHardwareAcceleration": false,
    "localAppLang": "en",
    "localOutputPath": "***",
    "obs": {
      "enable": true,
      "port": "4444",
      "password": "***",
      "mediaScene": "Media",
      "cameraScene": "Stage (wide)",
      "useV4": false,
      "zoomScene": "Zoom Speaker",
      "imageScene": null
    },
    "offline": false,
    "outputFolderDateFormat": "DD-MM-YYYY - dddd",
    "theme": "system",
    "zoom": {
      "enable": false,
      "name": "West Hills",
      "id": "***",
      "password": "***",
      "spotlight": true,
      "hideComponent": true,
      "autoRename": "***",
      "autoStartMeeting": true,
      "autoStartTime": 1
    }
  },
  "cong": {
    "server": null,
    "port": null,
    "user": null,
    "password": null,
    "dir": null
  },
  "media": {
    "autoPlayFirst": false,
    "autoPlayFirstTime": 5,
    "enableMediaDisplayButton": true,
    "enableMp4Conversion": false,
    "enablePp": false,
    "enableSubtitles": false,
    "enableVlcPlaylistCreation": false,
    "excludeLffImages": true,
    "excludeTh": true,
    "hideMediaLogo": false,
    "hideWinAfterMedia": false,
    "includePrinted": false,
    "keepOriginalsAfterConversion": false,
    "lang": "E",
    "langFallback": null,
    "langSubs": null,
    "langUpdatedLast": "2023-02-17T14:58:21.534Z",
    "maxRes": "720p",
    "mediaWinShortcut": "Alt+Z",
    "ppBackward": null,
    "ppForward": null,
    "preferredOutput": 2779098405,
    "presentShortcut": "Alt+D"
  },
  "meeting": {
    "autoStartMusic": false,
    "enableMusicButton": false,
    "enableMusicFadeOut": false,
    "coWeek": "2023-05-09",
    "musicFadeOutTime": 5,
    "musicFadeOutType": "smart",
    "musicVolume": 100,
    "mwDay": 3,
    "mwStartTime": "07:30",
    "shuffleShortcut": "Alt+K",
    "specialCong": false,
    "weDay": 6,
    "weStartTime": "10:00"
  },
  "__internal__": {
    "migrations": {
      "version": "23.4.0"
    }
  }
}
```

**Comment by mtdvlpr** [comment] 2023-04-02 19:04
@Tdanforth, does this happen consistently, occasionally or scarcely?

**Comment by Tdanforth** [comment] 2023-04-02 19:07
Well, consistent for this week. It seemed like previous weeks it was occasionally.

**Comment by Tdanforth** [comment] 2023-04-02 19:09
It's very strange. I tested showing a image and hiding it. It acted normally.

**Comment by Tdanforth** [comment] 2023-04-02 19:48
What I've done previously to stop this behavior is to restart M3. What happened this morning is I went out of the media controller to submit the bug.  I forgot my GitHub password and had to reset it. So I returned to the media controller because a picture needed to be shown. This bug didn't happen again for the rest of the meeting. I created this issue from the settings page at the end of the meeting without restarting M3.

**Comment by sircharlo** [comment] 2023-04-04 03:20
Not sure if this if related, but at the last meeting the av operator had to press play twice for the picture to show up: first time yeartext fades to black then back to yeartext, then second time played normally. 
I think it was related to using the "hide on Zoom" button on the previous picture.

**Comment by mtdvlpr** [comment] 2023-04-08 19:32
Since it's not consistently reproducible, not blocking, and we're working on [a new major release](https://github.com/sircharlo/meeting-media-manager/discussions/1757) with "fresh" code, I'm closing this in the hopes that it's fixed in the upcoming major release.

**Closed by mtdvlpr** 2023-04-08 19:32 UTC
Labels: bug
