### ISSUE TITLE
Unable to select media presentation window in Zoom on macOS

### ISSUE THREAD

**Issue by rickinhissmart** [sircharlo/meeting-media-manager#382] opened 2022-05-31 22:42 UTC
<img width="1863" alt="Screenshot  " src="https://user-images.githubusercontent.com/14828029/171295101-5871e8d3-844b-430d-b4e7-e8e0d3a1f00c.png">
hello,many thanks for hard work improving your app

zoom does not seem able to share screen of your app ie (set as in m3 second monitor or  in a separate window, only giving option for settings window to share.

spec, MacOS Monterey
MacBook Pro  2021
apple m1 pro
16 gb mem
zoom

**Comment by sircharlo** [comment] 2022-06-01 01:09
I can't reproduce this on Windows:
![image](https://user-images.githubusercontent.com/1275666/171308130-4ed56764-e5ef-486d-80d3-a851af041c09.png)

I'll try to play around a bit and see if I can figure something out.

**Comment by rickinhissmart** [comment] 2022-06-01 20:25
yes you can send test build and will try for you

**Comment by rickinhissmart** [comment] 2022-06-07 09:39
Do you have a test beta to try in mac ?

**Comment by sircharlo** [comment] 2022-06-07 16:35
Try this alpha dev package: https://we.tl/t-Y6BtQMuj3u

Note that it is not functional and only to be used for debugging.
It should open a maximum of 4 media windows. They might not all work, but that's ok. We just want to see what Zoom sees.
Please let me know the result in the Zoom sharing window. 

For example, on Windows, this is what I see: 

![image](https://user-images.githubusercontent.com/1275666/172435069-f1b0d96b-3481-4d25-8441-284b88c3a702.png)

**Comment by rickinhissmart** [comment] 2022-06-07 21:14
<img width="1983" alt="Screenshot 2022-06-07 at 17 57 43" src="https://user-images.githubusercontent.com/14828029/172483618-8cf1279d-9e4c-405e-bc6f-dc569d2615c6.png">

does this help, kind regards

**Comment by sircharlo** [comment] 2022-06-07 21:40
It actually does!

Try this?
https://we.tl/t-Qdw9WX3Zpr

**Comment by rickinhissmart** [comment] 2022-06-07 22:17
<img width="1980" alt="Screenshot 2022-06-07 at 23 15 47" src="https://user-images.githubusercontent.com/14828029/172492317-e77d6b64-a45b-4848-aa31-7d00b2975ade.png">

still no presentation window

**Comment by rickinhissmart** [comment] 2022-06-07 22:41
hey sircharlo  , I have also just tried on intel Mac running Big Sur 
with 5.10.6 (7526) zoom 
and latest version 5.10.7 (7748).zoom
it's also having the same issue.

**Comment by sircharlo** [comment] 2022-06-08 13:53
Ok; this is really a quirk of how Electron creates windows on macOS, combined with the always-on-top "feature".
If you can, please try the two versions included in this link and let me know: https://we.tl/t-8VLQZ841im

**Comment by sircharlo** [comment] 2022-06-08 17:08
Awesome! One last thing to ask you: in either version, are you able to put other windows on top of the black media window, or is it "always on top"?
Thanks for your help

**Comment by sircharlo** [comment] 2022-06-08 17:35
Well I'd like the presentation window to always be on top, but on macOS that clearly leads to issues with Zoom sharing, so I think I'll have to leave that as a Windows-only feature unfortunately until Electron or Zoom solve the underlying bug.

Better a window that isn't on top than no window at all!

**Comment by sircharlo** [comment] 2022-07-11 21:15
Fixed in the latest release (22.7.0)

**Closed by sircharlo** 2022-07-11 21:15 UTC
Labels: bug, implemented
