### ISSUE TITLE
[Feature]: Add introduction, index and appendixes to the Study Bible import

### ISSUE THREAD

**Issue by ux-git** [sircharlo/meeting-media-manager#3481] opened 2024-11-21 22:55 UTC
### Is your feature request related to a problem?

It would be useful for schools and field service meetings.

### Describe the solution you'd like

Perhaps the tabs can be added, just like in the JWL Bible? Introduction, Books, Index, Appendix A, Appendix B. There are some printed versions of the media which are also often useful.

By following the known pattern we will make it easier to import this additional media.

### Describe alternatives you've considered

Open JW Library instead, or open the jw.org / wol.jw.org

### Additional context

The books layout can be optimized to fit more books and use the window size better by moving the book names inside of the image. And perhaps making the gaps between books smaller. Looks pretty good:

<img width="1278" alt="Screenshot 2024-11-21 at 23 53 02" src="https://github.com/user-attachments/assets/651ea9b8-403c-4328-8af9-211a53b16f5d">

It won't really help with media on other tabs, since there are more desciptive text, but at least for the default tab that will be used the most often it would make sense.

### Confirmations

- [X] I confirm that I have read the documentation website.
- [X] I confirm that I have searched through the existing issues to make sure my feature request is not a duplicate.
- [X] I confirm that I have searched through the existing discussions to make sure my feature request is not a duplicate.

**Comment by sircharlo** [comment] 2024-11-24 12:41
From what I understand, it seems like this is definitely possible, but we'd have to change the underlying method we use to get media. 

@mtdvlpr Do you think this is worth it? We'd have to go from JSON parsing to JWPUB processing (`getDbFromJWPUB({ pub: 'nwtsty' })`).

**Comment by sircharlo** [comment] 2024-11-24 14:01
> > @mtdvlpr Do you think this is worth it? We'd have to go from JSON parsing to JWPUB processing (`getDbFromJWPUB({ pub: 'nwtsty' })`).
> 
> It would be nice to have the appendices as well! I tried finding the media gallery refs in the nwtsty jwpub, but couldn't find it. That's why I went for the json approach.

They're all there in the JWPUB , from what I can see...

**Comment by mtdvlpr** [comment] 2024-11-24 14:47
I'm sure I just wasn't looking in the right place.

**Comment by mtdvlpr** [comment] 2024-11-25 09:45
I see them now😄. I guess I was either looking at the regular bible or the Dutch study bible before...

**Comment by sircharlo** [comment] 2024-11-25 15:41
Yeah, we can add it to the roadmap. It'll be a refactor but it's not crucial in any way. Meeting media is the focus of this app :)

**Comment by sircharlo** [comment] 2024-11-28 16:52
Will be released in the next version!

**Comment by ux-git** [comment] 2024-11-28 16:59
@sircharlo the task only lasted three days in the "let's do it later" roadmap, great approach 😆

**Comment by ux-git** [comment] 2024-11-29 23:00
@sircharlo 
1. could you add some more bottom padding or a full-width divider  for each child in the list? Right now I find it easy to mix up whether the verse is above or below the current image (when scrolled to the middle of the image list). 

<img width="363" alt="Screenshot 2024-11-29 at 23 51 51" src="https://github.com/user-attachments/assets/742a61f0-817d-4a16-8061-298316908c2c">

2. And what do you think about making the image previews smaller to fit more images in the pop-up window height?
<img width="1058" alt="Screenshot 2024-11-29 at 23 56 55" src="https://github.com/user-attachments/assets/b550ab66-67f7-47c9-b0d3-50ce6cf0ced7">

3. Also, why does the app need to have this slightly lighter background for the media/chapter content? I'm not really sure if adds something to the user experience, but seems like it adds separation between the top, middle and bottom areas. Is that on purpose? 

4. When I want to click on an Appendix, I see the 'forbidden' type of cursor (at least in German). Could you implement a tooltip to give some content about why can't user click on any of the tabs? Or to make them inactive, if the app can't fetch any content for certain tabs.

**Comment by sircharlo** [comment] 2024-12-01 13:56
> 1. could you add some more bottom padding or a full-width divider  for each child in the list? Right now I find it easy to mix up whether the verse is above or below the current image (when scrolled to the middle of the image list). I personally can manage that, but I'm thinking about other brothers.

Done!

> 2. And what do you think about making the image previews smaller to fit more images in the pop-up window height?

Done!

> 3. Also, why does the app need to have this slightly lighter background for the media/chapter content? I'm not really sure if adds something to the user experience, but seems like it adds separation between the top, middle and bottom areas. Is that on purpose?

It most certainly is not. 😆  
Fixed!


> 4. When I want to click on an Appendix, I see the 'forbidden' type of cursor (at least in German). Could you implement a tooltip to give some content about why can't user click on any of the tabs? Or to make them inactive, if the app can't fetch any content for certain tabs.

This is not intended; you're supposed to see local or English media, whichever is available. I'll fix the logic so that English shows up as intended.
But I can definitely add a tooltip to explain when a media section really is empty.

**Closed** 2024-12-04 23:38 UTC
Labels: enhancement, implemented
