### ISSUE TITLE
Extract .jwplaylist files from a monitored folder.

### ISSUE THREAD

**Issue by joaochris** [sircharlo/meeting-media-manager#3360] opened 2024-11-16 10:08 UTC
### Is your feature request related to a problem?

Not.

### Describe the solution you'd like

It would be great to have this feature because, with a mobile phone, you could simply upload a .jwplaylist file to the cloud. Then, when the computer in the Kingdom Hall is turned on, M3 would detect the file in the monitored folder and extract it, just like when we drag and drop a .jwplaylist file. 
Also, the option to add a song and include it in the playlist without needing to download it is wonderful. This way, it’s possible to have all the meeting's media included in a single file.

Is it possible to implement this?

### Confirmations

- [X] I confirm that I have read the documentation website.
- [X] I confirm that I have searched through the existing issues to make sure my feature request is not a duplicate.
- [X] I confirm that I have searched through the existing discussions to make sure my feature request is not a duplicate.

**Comment by mtdvlpr** [comment] 2024-11-16 12:06
We discussed this for pdfs and svgs as well, but decided not to support it, because we want to keep the watched folder readonly and not write to it.

**Comment by mtdvlpr** [comment] 2024-11-16 19:43
@sircharlo, what do you think? Could we do this without writing to the watched folder?

**Comment by ux-git** [comment] 2024-11-16 23:08
@mtdvlpr start a script upon a startup to detect .jwplaylist in the momnitored folder and write the data into the app's main folder?

**Comment by fschein** [comment] 2024-11-16 23:56
I second this feature 😁

**Comment by e-Feitosa** [comment] 2024-11-17 00:27
Taking advantage of this topic, it seems to be a BUG, every video (.MP4) file placed in the folder, the M3 converts image (.jpg), see in print, I added two videos for testing and see that has an image of each video in format . jpg and these images appear in the media for the week.
![image](https://github.com/user-attachments/assets/2641413b-7e77-465e-a8b7-d29fd55a8523)

**Comment by joaochris** [comment] 2024-11-17 01:30
> Aproveitando esse tópico, parece ser um BUG, ​​todo arquivo de vídeo (.MP4) colocado na pasta, o M3 converte imagem (.jpg), veja na impressão, adicionei dois vídeos para teste e veja que tem uma imagem de cada vídeo no formato .jpg e essas imagens aparecem na mídia da semana.
> 
> ![imagem](https://private-user-images.githubusercontent.com/90984283/386898126-2641413b-7e77-465e-a8b7-d29fd55a8523.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MzE4MDcxNzksIm5iZiI6MTczMTgwNjg3OSwicGF0aCI6Ii85MDk4NDI4My8zODY4OTgxMjYtMjY0MTQxM2ItN2U3Ny00NjVlLWE4YjctZDI5ZmQ1NWE4NTIzLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDExMTclMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQxMTE3VDAxMjc1OVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWU4Y2Y1Y2UxYWRhNzdiODNhNWUzNzQ3ODgzNjY4ZTFhZjc3MzU1ZmNlYjgwYzFiNDQwYTJkZWFjMmJlMDQzOWMmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0In0.vvMuNwiCt60eOrUBg3ng0QiPe6rVPZ0DK1aGOd8ExNE)
> 
> ## Observação:
> Seria interessante se esse recurso de conversão acontecesse com algum PDF colocado na pasta.

Verdade, acontece o mesmo aqui, até achei que não fosse. Mas parece ser algum bug.

**Comment by sircharlo** [comment] 2024-11-18 16:36
Our approach for the moment as we're slowly building this feature up, is to **not write** anything into the watched folder and **not delete** anything from it either.

If we add the feature of extracting JWPLAYLIST files, converting PDFs, etc., we'd need a local area where these extracted/converted files would live. They would **not** get added to the watched folder.

**Comment by sircharlo** [comment] 2024-11-18 16:37
> Taking advantage of this topic, it seems to be a BUG, every video (.MP4) file placed in the folder, the M3 converts image (.jpg), see in print, I added two videos for testing and see that has an image of each video in format . jpg and these images appear in the media for the week.

This shouldn't happen. I'll look into that.

**Comment by sircharlo** [comment] 2024-11-18 16:41
> > Taking advantage of this topic, it seems to be a BUG, every video (.MP4) file placed in the folder, the M3 converts image (.jpg), see in print, I added two videos for testing and see that has an image of each video in format . jpg and these images appear in the media for the week.
> 
> This shouldn't happen. I'll look into that.

Fixed in 46123a78d7d27bc4688335f6ebd7b33b34572300.

**Comment by sircharlo** [comment] 2024-11-18 16:43
> > Taking advantage of this topic, it seems to be a BUG, every video (.MP4) file placed in the folder, the M3 converts image (.jpg), see in print, I added two videos for testing and see that has an image of each video in format . jpg and these images appear in the media for the week.
> 
> This shouldn't happen. I'll look into that.

Does this happen even in the latest version?

**Comment by e-Feitosa** [comment] 2024-11-18 17:43
> Does this happen even in the latest version?

Yes, I am using **version 24.11.4**.

**Comment by e-Feitosa** [comment] 2024-11-18 17:57
> Nossa abordagem no momento, à medida que estamos construindo lentamente esse recurso, é **não gravar** nada na pasta assistida e **também não excluir** nada dela.
> 
> Se adicionarmos o recurso de extrair arquivos JWPLAYLIST, converter PDFs, etc., precisaríamos de uma área local onde esses arquivos extraídos/convertidos ficariam. Eles **não** seriam adicionados à pasta assistida.

Obrigado pelos esclarecimentos. 
Pelo que entendi, nesse caso, seria necessário configurar uma segunda opção para definir um novo caminho para uma pasta local onde os arquivos (pdf/jwplaylist) seriam extraídos e, em seguida, exibidos na lista de mídias adicionadas.

**Comment by sircharlo** [comment] 2024-11-19 19:28
Initial implementation in 0718a0daf396b29832b88ad20a2e1bb6eddef14a.

**Comment by sircharlo** [comment] 2024-11-19 19:33
> Yes, I am using **version 24.11.4**.

Please open a new issue if this behavior still persists in 24.11.5.

**Comment by joaochris** [comment] 2024-11-19 19:49
> Initial implementation in 0718a0daf396b29832b88ad20a2e1bb6eddef14a.

Thank you very much.

**Comment by joaochris** [comment] 2024-11-20 22:27
Hi, @sircharlo 

I was testing the JW playlists feature in the watched folder and it's great, thanks!
The video timing issue has been fixed.

But I noticed some problems.

1 - When adding media from a .jwplaylist file it appears that it was added manually (In this case, it should appear from a monitored folder)
![image](https://github.com/user-attachments/assets/3799a898-0f01-4fbe-9b4a-18e5815b5f84)

2 - The bug still occurs where when sending a video to the monitored folder it creates a thumbnail of the video.
![image](https://github.com/user-attachments/assets/91a0bbc9-dbf3-43a7-92d0-94ccc20a10a9)

3 - When right-clicking on media added from a monitored folder, the delete media button appears. When I click, nothing happens.
![image](https://github.com/user-attachments/assets/3a1fc631-d0e7-4866-b80d-b97321e2884a)

4 - In some cases the thumbnail is cut off, it does not fill the entire square. I tested with videos from the circuit overseer's media that are in the restricted area. There is inconsistency, sometimes it fills the entire square and other times it doesn't. :D
![Capturar 22](https://github.com/user-attachments/assets/53dfd940-81ac-473d-8ad2-e7bf3b2e8adc)

**Comment by sircharlo** [comment] 2024-11-20 22:33
> I was testing the JW playlists feature in the watched folder and it's great, thanks! The video timing issue has been fixed.

Glad to hear it!

> 1 - When adding media from a .jwplaylist file it appears that it was added manually (In this case, it should appear from a monitored folder)

It _was_ added "manually"; the JWLPLAYLIST file is still in the watched folder, untouched, and the media files were extracted from it and added as if the user did it themselves. Behavior as intended.

> 2 - The bug still occurs where when sending a video to the monitored folder it creates a thumbnail of the video. 

Could you share an example playlist and your workflow? I can't reproduce this.

> 3 - When right-clicking on media added from a monitored folder, the delete media button appears. When I click, nothing happens. 

I'll look into this!

> 4 - In some cases the thumbnail is cut off, it does not fill the entire square. I tested with videos from the circuit overseer's media that are in the restricted area. There is inconsistency, sometimes it fills the entire square and other times it doesn't. 

This depends on if the thumbnail can be fetched from the API or if it has to be extracted from the video. I'd say this isn't a huge problem.

**Comment by joaochris** [comment] 2024-11-21 00:16
> It _was_ added "manually"; the JWLPLAYLIST file is still in the watched folder, untouched, and the media files were extracted from it and added as if the user did it themselves. Behavior as intended.

Ah, true, I had forgotten this point.

> Could you share an example playlist and your workflow? I can't reproduce this.

For example using OneDrive.... 
https://github.com/user-attachments/assets/1ed5f664-edb9-4fb9-b4a4-a5029330d06f



With the video:

https://github.com/user-attachments/assets/69ef3010-7c2c-4061-a317-9c7728e17ddb

> This depends on if the thumbnail can be fetched from the API or if it has to be extracted from the video. I'd say this isn't a huge problem.

I noticed this in the console :) It's really not a problem, but it would be interesting if it could be resolved to maintain the standard ;)

**Comment by sircharlo** [comment] 2024-11-21 13:01
> 
> For example using OneDrive.... https://github.com/user-attachments/assets/1ed5f664-edb9-4fb9-b4a4-a5029330d06f
> 
> With the video:
> 
> I noticed this in the console :) It's really not a problem, but it would be interesting if it could be resolved to maintain the standard ;)

Could you open two new seperate issues please? One for the thumbnail getting created, and one for the inconsistent thumbnails.
Just to keep things tidy 😄

**Comment by joaochris** [comment] 2024-11-21 13:09
> > Por exemplo, usando o OneDrive.... https://github.com/user-attachments/assets/1ed5f664-edb9-4fb9-b4a4-a5029330d06f
> > Com o vídeo:
> > Notei isso no console :) Realmente não é um problema, mas seria interessante se pudesse ser resolvido para manter o padrão ;)
> 
> Você poderia abrir três novas edições separadas, por favor?
> 
> * Um para a miniatura sendo criada a partir de vídeos
> * Um para as miniaturas inconsistentes
> * Um para o botão de exclusão de mídia que aparece ao clicar com o botão direito na mídia adicionada de uma pasta monitorada
> 
> Só para manter as coisas organizadas 😄

Posso sim!

**Closed** 2024-11-21 21:55 UTC
Labels: enhancement, implemented
