### ISSUE TITLE
[Bug]: Downloading media in the wrong order

### ISSUE THREAD

**Issue by e-Feitosa** [sircharlo/meeting-media-manager#2134] opened 2023-09-11 20:11 UTC
### What happened?

Last week and this week, M3 downloaded a video out of order. It's a video in treasures (revisit), and the M3 downloads like a name starting 2020

![image](https://github.com/sircharlo/meeting-media-manager/assets/90984283/f28cc642-faac-464f-b720-4f5ed667de90)

### To Reproduce

Download the media of the week 20230911

### What did you expect to happen?

The media Video of the return visit should be in the do your best section...

### Version

v23.8.1

### What platform are you seeing the problem on?

Windows 11

### Screenshots
![image](https://github.com/sircharlo/meeting-media-manager/assets/90984283/d6a961af-08a9-41e3-bc90-4c8d8a7748e8)

**Comment by sircharlo** [comment] 2023-09-12 17:31
I can't reproduce this:

![image](https://github.com/sircharlo/meeting-media-manager/assets/1275666/88f0dbc7-8600-4e05-af03-8d291ab0585c)

**Comment by e-Feitosa** [comment] 2023-09-12 22:41
The language is Brazilian Portuguese (pt-BR), in the photo you sent it is pt-PT (Portugal)

**Comment by sircharlo** [comment] 2023-09-13 14:18
> The language is Brazilian Portuguese (pt-BR), in the photo you sent it is pt-PT (Portugal)
> 
> ✅ In the language pt-PT (Portugal) OK as shown in the image above and its test ![image](https://user-images.githubusercontent.com/90984283/267485024-7b8264d9-38e1-4bba-b99b-e09b30a3f7e6.png)
> 
> ❌ In the pt-BR (Brazil) language it does not download correctly ![image](https://user-images.githubusercontent.com/90984283/267485060-a98bd7c4-b9e2-4b02-9692-244bc948bd56.png)

Got it! Fixed in https://github.com/sircharlo/meeting-media-manager/commit/873a53f5ec6fa57179f5e6bd0ec8aa3dc5f16ee8.

**Comment by sircharlo** [comment] 2023-10-16 01:29
bump

**Closed** 2023-10-22 08:23 UTC
Labels: bug, implemented
